### ISSUE TITLE
Error while building (npm run build)

### ISSUE THREAD

**Issue by shamoh19** [start-angular/SB-Admin-BS4-Angular-5#151]
ERROR in Error: Template parse errors:
Can't bind to 'up' since it isn't a known property of 'div'. ("
            </div>
            <div class="col text-right">
                <div ngbDropdown [ERROR ->][up]="true" class="d-inline-block">
                    <button class="btn btn-outline-primary" id="d"): ng:///Applications/Workspace/Angular/Ang_Bs/src/app/layout/bs-component/components/dropdown/dropdown.component.html@15:33
    at Error (native)
    at syntaxError (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at TemplateParser.parse (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/compiler/bundles/compiler.umd.js:12826:19)
    at AotCompiler._compileComponent (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/compiler/bundles/compiler.umd.js:24054:39)
    at /Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/compiler/bundles/compiler.umd.js:23935:55
    at Array.forEach (native)
    at AotCompiler._compileImplFile (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/compiler/bundles/compiler.umd.js:23918:20)
    at /Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/compiler/bundles/compiler.umd.js:23829:87
    at Array.map (native)
    at AotCompiler.emitAllImpls (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/compiler/bundles/compiler.umd.js:23829:52)
    at CodeGenerator.emit (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/compiler-cli/src/codegen.js:42:46)
    at /Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/compiler-cli/src/codegen.js:33:61
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by DocBradfordSoftware** [comment]
I "solved" this by editing src/app/layout/bs-component/components/dropdown/dropdown.component.html and removing the
```
[up]="true"
```
Not sure what the consequence of that was, but it got rid of the error.

**Comment by alpesh-patel93** [comment]
Use `placement` instead of `up`, Refer https://ngbootstrap.github.io/#/components/dropdown/api
