### ISSUE TITLE
Fails OOB: Cannot find modules 'webpack/lib/node/NodeTemplatePlugin'

### ISSUE THREAD

**Issue by kevindashgit** [start-angular/SB-Admin-BS4-Angular-5#169]
node `v8.9.1`
npm `5.5.1`
OSX `10.12.6`

All I did was run `npm install && npm start` as instructed - failed with:

```
> SB-Admin-BS4-Angular-5@4.0.0 start /Users/<USER>/temp/<FOLDER>
> ng serve --ec true

Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/<USER>/temp/<FOLDER>/node_modules/html-webpack-plugin/lib/compiler.js:11:26)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/<USER>/temp/<FOLDER>/node_modules/html-webpack-plugin/index.js:7:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! SB-Admin-BS4-Angular-5@4.0.0 start: `ng serve --ec true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the SB-Admin-BS4-Angular-5@4.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**(note <user> / <folder> bits in the stack trace were added by me)**

**Comment by sangwin** [comment]
+1.

**Comment by kevindashgit** [comment]
Thanks @sangwin that did the trick! Thanks!

**Comment by kevindashgit** [comment]
I should mention that `ng serve` did not work for me - but `npm start` did.
