### ISSUE TITLE
cannot able to install and start 

### ISSUE THREAD

**Issue by dmanims** [start-angular/SB-Admin-BS4-Angular-5#182]
cannot able to install,  its showing long time
 43% building modules 275/275 modules 0 active

|   | +-- is-fullwidth-code-point@2.0.0
|   | `-- strip-ansi@4.0.0
|   |   `-- ansi-regex@3.0.0
|   +-- which-module@2.0.0
|   +-- y18n@3.2.1
|   `-- yargs-parser@7.0.0
|     `-- camelcase@4.1.0
+-- yarn@1.3.2
`-- zone.js@0.8.18

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-beta.6 requires a peer of @angular/core@^4.0.3 but none was installed.
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-beta.6 requires a peer of @angular/common@^4.0.3 but none was installed.
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-beta.6 requires a peer of @angular/forms@^4.0.3 but none was installed.
npm WARN @schematics/angular@0.1.10 requires a peer of @angular-devkit/schematics@0.0.40 but none was installed.
npm WARN @schematics/schematics@0.0.10 requires a peer of @angular-devkit/schematics@0.0.40 but none was installed.

D:\Project\Develop\xampp\htdocs\SB-Admin-BS4-Angular-5-master\SB-Admin-BS4-Angular-5-master>npm start

> SB-Admin-BS4-Angular-5@4.0.0 start D:\Project\Develop\xampp\htdocs\SB-Admin-BS4-Angular-5-master\SB-Admin-BS4-Angular-5-master
> ng serve --ec true

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 12% building modules 24/32 modules 8 active ...r\platform-browser\esm5\animations.jsError: No module factory available for dependency type: ContextElementDependency
    at Compilation.addModuleDependencies (D:\Project\Develop\xampp\htdocs\SB-Admin-BS4-Angular-5-master\SB-Admin-BS4-Angular-5-master\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:215:21)
    at Compilation.processModuleDependencies (D:\Project\Develop\xampp\htdocs\SB-Admin-BS4-Angular-5-master\SB-Admin-BS4-Angular-5-master\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:204:8)
    at _this.buildModule.err (D:\Project\Develop\xampp\htdocs\SB-Admin-BS4-Angular-5-master\SB-Admin-BS4-Angular-5-master\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:359:14)
    at building.forEach.cb (D:\Project\Develop\xampp\htdocs\SB-Admin-BS4-Angular-5-master\SB-Admin-BS4-Angular-5-master\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:149:27)
    at Array.forEach (native)
    at callback (D:\Project\Develop\xampp\htdocs\SB-Admin-BS4-Angular-5-master\SB-Admin-BS4-Angular-5-master\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:149:13)
    at module.build (D:\Project\Develop\xampp\htdocs\SB-Admin-BS4-Angular-5-master\SB-Admin-BS4-Angular-5-master\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:176:11)
    at resolveDependencies (D:\Project\Develop\xampp\htdocs\SB-Admin-BS4-Angular-5-master\SB-Admin-BS4-Angular-5-master\node_modules\@angular\cli\node_modules\webpack\lib\ContextModule.js:165:4)
    at ContextModule.result.resolveDependencies (D:\Project\Develop\xampp\htdocs\SB-Admin-BS4-Angular-5-master\SB-Admin-BS4-Angular-5-master\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:423:25)
    at ContextModule.build (D:\Project\Develop\xampp\htdocs\SB-Admin-BS4-Angular-5-master\SB-Admin-BS4-Angular-5-master\node_modules\@angular\cli\node_modules\webpack\lib\ContextModule.js:105:8)
    at Compilation.buildModule (D:\Project\Develop\xampp\htdocs\SB-Admin-BS4-Angular-5-master\SB-Admin-BS4-Angular-5-master\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:151:10)
    at factoryCallback (D:\Project\Develop\xampp\htdocs\SB-Admin-BS4-Angular-5-master\SB-Admin-BS4-Angular-5-master\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:344:12)
    at D:\Project\Develop\xampp\htdocs\SB-Admin-BS4-Angular-5-master\SB-Admin-BS4-Angular-5-master\node_modules\@angular\cli\node_modules\webpack\lib\ContextModuleFactory.js:95:13
    at D:\Project\Develop\xampp\htdocs\SB-Admin-BS4-Angular-5-master\SB-Admin-BS4-Angular-5-master\node_modules\tapable\lib\Tapable.js:268:11
    at done.then (D:\Project\Develop\xampp\htdocs\SB-Admin-BS4-Angular-5-master\SB-Admin-BS4-Angular-5-master\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:425:28)
 43% building modules 275/275 modules 0 active

**Comment by PeppeDB** [comment]
Hi, 
I have the same problem.  Any ideas how to solve it?

**Comment by liyobi** [comment]
solved it.
Run again after webpack uninstall

1.npm uninstall --save-dev webpack
2.npm install
3.npm start

**Comment by dmanims** [comment]
thank you

**Comment by inferiore** [comment]
hi
i have same problem... but this no work: "solved it.
Run again after webpack uninstall

1.npm uninstall --save-dev webpack
2.npm install
3.npm start"

Any idea for solve?
