### ISSUE TITLE
Cannot find module 'webpack/lib/node/NodeTemplatePlugin'

### ISSUE THREAD

**Issue by darrenjs** [start-angular/SB-Admin-BS4-Angular-5#188]
Hi,

On first attempt to clone the repo, run `npm install --save` and then after that `npm start` , I get following error:

```
Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/darrens/work/dev/src/c++/projx/www/SB-Admin-BS4-Angular-5/node_modules/html-webpack-plugin/lib/compiler.js:11:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/darrens/work/dev/src/c++/projx/www/SB-Admin-BS4-Angular-5/node_modules/html-webpack-plugin/index.js:7:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

I think this can be resolved adding a webpack dependency to the package.json.

**Comment by nitinkumarmishra** [comment]
just remove package-lock.json and node_modules then `npm install`

**Comment by darrenjs** [comment]
works, thanks!

**Comment by aziz-herch** [comment]
Can you please clarify, what are node modules ?
